name: Deploy lwjgl3 modpack

permissions:
  contents: write
  deployments: write

on:
  push:
    tags:
      - '*-lwjgl3-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the version
        run: |
          echo VERSION=$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $1}') >> $GITHUB_ENV
          echo LWIGL3_VERSION=$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $3}') >> $GITHUB_ENV

      - name: Set the version
        run: |
          MODPACKVERSION=${{ env.VERSION }}
          sed -i -e "s/MODPACKVERSION/${MODPACKVERSION}/g" ./manifest.json
          sed -i -e "s/MODPACKVERSION/${MODPACKVERSION}/g" ./cmmc/instance.cfg

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Remove lwjgl3 not supported mods
        run: python buildtools/gen-lwjgl3-manifest.py

      - name: Install dependencies
        run: |
          cp -vf ./cmmc/manifest.json ./manifest.json
          python -m pip install --upgrade pip
          pip install -r ./buildtools/requirements.txt

      - name: Run Python
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: python buildtools/mod-install.py

      - name: Archive Release MMC
        run: |
          cp -rvf ./cmmc/bansoukou/ ./overrides/
          rm -Rf ./cmmc/bansoukou/
          mv -vf ./overrides/ .minecraft/
          cp -rvf ./cmmc/* ./
          rm -rf .minecraft/mods/.gitkeep
          rm -rf .minecraft/resourcepacks/.gitkeep
          zip -r ./LegacyCraft-${{ env.VERSION }}-lwjgl3-${{ env.LWIGL3_VERSION }}-mmc.zip ./libraries/ ./patches/ ./mmc-pack.json ./instance.cfg .minecraft/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            ./LegacyCraft-${{ env.VERSION }}-lwjgl3-${{ env.LWIGL3_VERSION }}-mmc.zip
